import type { Metadata } from "next";
import "./globals.css";
import { Navbar, Footer } from "@/sections";
import { Nunito, Quicksand } from 'next/font/google'


const nunito = Nunito({
  subsets: ['latin'],
  weight: ["200", "300", "400", "500", "600",  "700", "800",  "900"],
  variable: "--font-nunito"
})


const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ["300", "400", "500", "600",  "700"],
  variable: "--font-quicksand"
})



export const metadata: Metadata = {
  title: "Creative Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative ${nunito.variable} ${quicksand.variable}`}>
        <Navbar />
          <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
